apiVersion: v1
kind: PersistentVolume
metadata:
  name: kong-postgresql-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/kong-postgresql-pv
  persistentVolumeReclaimPolicy: Delete