// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	publishserviceapi "oransc.org/nonrtric/capifcore/internal/publishserviceapi"
)

// APIRegister is an autogenerated mock type for the APIRegister type
type APIRegister struct {
	mock.Mock
}

// AreAPIsRegistered provides a mock function with given fields: serviceDescriptions
func (_m *APIRegister) AreAPIsRegistered(serviceDescriptions *[]publishserviceapi.ServiceAPIDescription) bool {
	ret := _m.Called(serviceDescriptions)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*[]publishserviceapi.ServiceAPIDescription) bool); ok {
		r0 = rf(serviceDescriptions)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// IsAPIRegistered provides a mock function with given fields: aefId, path
func (_m *APIRegister) IsAPIRegistered(aefId string, path string) bool {
	ret := _m.Called(aefId, path)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(aefId, path)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

type mockConstructorTestingTNewAPIRegister interface {
	mock.TestingT
	Cleanup(func())
}

// NewAPIRegister creates a new instance of APIRegister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAPIRegister(t mockConstructorTestingTNewAPIRegister) *APIRegister {
	mock := &APIRegister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
